#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Project22.Resource", IsApplication=true)]

namespace Project22
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040002
			public const int activity_horizontal_margin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int activity_vertical_margin = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int nav_header_height = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int nav_header_vertical_spacing = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_shape = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cell_shape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int gradient_bg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gradient_bg_alternate = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int gradient_bg_hover = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int gradient_bg_hover_alternate = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int image_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int input_shape = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int list_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int list_selector_alternate = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int search = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070017
			public const int btnPersona = 2131165207;
			
			// aapt resource value: 0x7f07000c
			public const int btninsertar = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int dpfechanac = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int etapellidos = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int etcorreo = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int etdetalle = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int etdireccion = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int etestadocivil = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int etid = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int etidentificacion = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int etnombre = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int etsexo = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int ettelefono = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int ettiposangre = 2131165194;
			
			// aapt resource value: 0x7f070016
			public const int lr_deleteBtn = 2131165206;
			
			// aapt resource value: 0x7f070013
			public const int lr_descriptin = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int lr_email = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int lr_fullName = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int lr_mobile = 2131165199;
			
			// aapt resource value: 0x7f070015
			public const int lr_viewBtn = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int personaListBtnAdd = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int personaListBtnSearch = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int personaListListView = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int personaListTxtSearch = 2131165210;
			
			// aapt resource value: 0x7f070018
			public const int tableLayout = 2131165208;
			
			// aapt resource value: 0x7f070011
			public const int tableRow1 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int textView1 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int tlBtns = 2131165204;
			
			// aapt resource value: 0x7f07000d
			public const int tlMain = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEditPersona = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int list_row_persona_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Personas = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int button_style = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int input_style = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
